from pydantic import BaseModel, Field, EmailStr
from typing import List, Optional, Dict


# PERSONAL INFORMATION
class PersonalInfo(BaseModel):
    name: str = Field(..., description="Full name of the candidate")
    email: EmailStr = Field(..., description="Email address")
    phone: Optional[str] = Field(None, description="Phone number")
    linkedin: Optional[str] = Field(None, description="LinkedIn profile URL")
    github: Optional[str] = Field(None, description="GitHub profile URL")
    location: Optional[str] = Field(None, description="Candidate's location")


# EDUCATION
class EducationEntry(BaseModel):
    institution: str
    degree: str
    field_of_study: Optional[str] = None
    year_of_completion: Optional[int] = None
    gpa: Optional[float] = None


# EXPERIENCE
class ExperienceEntry(BaseModel):
    title: str
    company: str
    location: Optional[str] = None
    start_date: Optional[str] = Field(None, description="Start date in YYYY-MM format")
    end_date: Optional[str] = Field(None, description="End date in YYYY-MM format or 'Present'")
    responsibilities: Optional[List[str]] = Field(None, description="List of responsibilities or achievements")


# PROJECTS
class ProjectEntry(BaseModel):
    title: str
    description: Optional[str] = None
    tech_stack: Optional[List[str]] = None
    link: Optional[str] = None


# CERTIFICATIONS
class CertificationEntry(BaseModel):
    name: str
    issuer: Optional[str] = None
    year: Optional[int] = None


# MAIN RESUME MODEL
class ResumeModel(BaseModel):
    personal_info: Optional[PersonalInfo] = None
    education: Optional[List[EducationEntry]] = None
    experience: Optional[List[ExperienceEntry]] = None
    skills: Optional[List[str]] = None
    certifications: Optional[List[CertificationEntry]] = None
    achievements: Optional[List[str]] = None
    projects: Optional[List[ProjectEntry]] = None

    # Raw extracted text (from PDF/DOCX)
    raw_text: Optional[str] = None

    # Cleaned + normalized text (for LLM)
    cleaned_text: Optional[str] = None

    # Enhanced résumé output
    enhanced_resume: Optional[str] = None

    # List of changes or suggestions generated by LLM
    enhancements: Optional[Dict] = Field(
        None, description="AI-generated recommendations and changes"
    )
